# Generated by Django 5.2.4 on 2025-11-27 12:30

import django.db.models.deletion
import gestionCitas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[gestionCitas.validators.validar_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('rut_vet', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[gestionCitas.validators.validar_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo_chip', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[gestionCitas.validators.validar_numeros])),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='gestionCitas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('CANCELADO_VET', 'Cancelado por veterinario'), ('CANCELADO_PAC', 'Cancelado por paciente')], default='DISPONIBLE', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='gestionCitas.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='gestionCitas.veterinario')),
            ],
        ),
    ]
