# Generated by Django 5.2.4 on 2025-11-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueatencion',
            name='id',
        ),
        migrations.AddField(
            model_name='bloqueatencion',
            name='codigo_atencion',
            field=models.CharField(default='a001', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloqueatencion',
            name='codigo_cita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='codigo_chip',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
