# Generated by Django 5.2.4 on 2025-11-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0002_remove_bloqueatencion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueatencion',
            name='motivo',
        ),
        migrations.AddField(
            model_name='bloqueatencion',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
