# Generated by Django 5.2.4 on 2025-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0003_remove_bloqueatencion_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueatencion',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('CANCELADO_VET', 'Cancelado por veterinario'), ('CANCELADO_PAC', 'Cancelado por paciente')], default='DISPONIBLE', max_length=20),
        ),
    ]
